cocktailProject/cocktailProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls'))
]

cocktailProject/core/urls.py
from django.urls import path
from .views import CocktailListView,DeleteCocktailView, EditCocktailView, CreateCocktailView,DetailsCocktailView, test_one, test_two, test_three

urlpatterns = [
    path('',CocktailListView.as_view(),name='dashboard'),
    path('create/',CreateCocktailView.as_view(),name='create'),
    path('details<int:pk>/',DetailsCocktailView.as_view(),name='details'),
    path('edit/<int:pk>/',EditCocktailView.as_view(),name='edit'),
    path('delete/<int:pk>/',DeleteCocktailView.as_view(),name='delete'),
    path('one/',test_one,name='one'),
    path('two/',test_two,name='two'),
    path('three/',test_three,name='three'),
]

cocktailProject/core/models.py
from django.db import models

# Create your models here.
class Cocktail(models.Model):
    COCKTAIL_TYPES = [
        ('shaken', 'Shaken'),
        ('stirred', 'Stirred'),
        ('built', 'Built'),
        ('frozen', 'Frozen'),
        ('blended', 'Blended'),
    ]

    STYLE_CHOICES = [
        ('tiki', 'Tiki'),
        ('modern', 'Modern'),
        ('sour', 'Sour'),
    ]

    name = models.CharField(max_length=100)
    type = models.CharField(max_length=10, choices=COCKTAIL_TYPES, blank=True, null=True)
    style = models.CharField(max_length=10, choices=STYLE_CHOICES, blank=True, null=True)
    instructions = models.TextField(blank=True, null=True)
    creator = models.CharField(max_length=100, blank=True, null=True)  # New field

    def __str__(self):
        return self.name

class Ingredient(models.Model):
    TYPE_CHOICES = [
        ('spirit', 'Spirit'),
        ('modified_spirit', 'Modified Spirit'),
        ('citrus', 'Citrus'),
        ('bitters', 'Bitters'),
        ('liqueur', 'Liqueur'),
        ('sweetener', 'Sweetener'),
        ('fruit_puree', 'Fruit/Puree'),
        ('herb_spice', 'Herb/Spice'),
        ('garnish', 'Garnish'),
        ('dairy_cream', 'Dairy/Cream'),
        ('syrup_flavoring', 'Syrup/Flavoring'),
        ('vegetable', 'Vegetable'),
        ('wine_fortified_wine', 'Wine/Fortified Wine'),
        ('extract', 'Extract'),
        ('ice', 'Ice'),
    ]

    name = models.CharField(max_length=100)
    ingredient_type = models.CharField(max_length=20, choices=TYPE_CHOICES)
    brand = models.CharField(max_length=100, blank=True, null=True)
    abv = models.DecimalField("Alcohol by Volume (%)", max_digits=5, decimal_places=1, blank=True, null=True)
    sweetness = models.DecimalField("Sweetness (%)", max_digits=5, decimal_places=2, blank=True, null=True)
    acid = models.DecimalField("Acid (%)", max_digits=5, decimal_places=2, blank=True, null=True)
    instructions = models.TextField("How to create", blank=True, null=True)

    def __str__(self):
        return f"{self.name}"

class CocktailIngredient(models.Model):
    cocktail = models.ForeignKey(Cocktail, related_name='ingredients', on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    quantity = models.FloatField(blank=True, null=True)
    unit = models.CharField(max_length=20, choices=[
        ('Slice', 'slice'),
        ('Wedge', 'wedge'),
        ('Drop', 'drop'),
        ('Dash', 'dash'),
        ('Milliliter', 'ml'),
        ('Ounce', 'oz'),
        ('Cup', 'c'),
    ], blank=True, null=True)
    
    def get_abbreviated_unit(self):
        abbreviations = {
            'milliliter': 'ml',
            'ounce': 'oz',
            'cup': 'c',
        }
        # Return the abbreviation if available; otherwise, return the full unit name
        return abbreviations.get(self.unit, self.unit)

    def __str__(self):
        return f'{self.quantity} {self.unit} of {self.ingredient.name}'

cocktailProject/templates/partials/card_list.html
<div x-cloak 
     x-data>
    <div>
        <span class="text-sm text-gray-600 font-semibold">Total: 
            <span 
                x-text="$store.visibleCount.count"
                ></span>
        </span>
    </div>
            <!-- No Results Found Message -->
            <div 
            x-cloak
            x-data
            x-show="$store.visibleCount.count === 0"
            x-transition:enter="ease-out duration-300" 
            x-transition:enter-start="opacity-0" 
            x-transition:enter-end="opacity-100" 
            x-transition:leave="ease-in duration-50" 
            x-transition:leave-start="opacity-100" 
            x-transition:leave-end="opacity-0" 
            class="items-center justify-center p-6 bg-gray-100 rounded-md border border-gray-300 text-gray-700"
            :class="$store.visibleCount.count === 0 ? 'flex' : 'hidden'"
                >
            <div class="text-center">
                <svg 
                    class="w-10 h-10 text-gray-400 mx-auto mb-4" 
                    xmlns="http://www.w3.org/2000/svg" 
                    fill="none" 
                    viewBox="0 0 24 24" 
                    stroke="currentColor" 
                    stroke-width="2"
                >
                    <path 
                        stroke-linecap="round" 
                        stroke-linejoin="round" 
                        d="M8 9l4-4m0 0l4 4m-4-4v12m4 4H8m4-4v4m4-4H8" 
                    />
                </svg>
                <h2 class="text-lg font-semibold">No results found for "<span x-text="$store.search.query"></span>"</h2>
                <p class="text-sm text-gray-500 mt-2">Try refining your search or using different keywords.</p>
                <c-button type="primary">Create New Cocktail</c-button>
            </div>
        </div>
        {% for item in cocktails_with_ingredients %}
            <c-card 
                    name="{{item.cocktail.name}}" 
                    creator="{{item.cocktail.creator}}"
                    type="{{item.cocktail.get_type_display}}"
                    drink_style="{{item.cocktail.get_style_display}}"
                    instructions="{{item.cocktail.instructions }}"
                    item_id="{{item.cocktail.id}}"
                    :ingredients="item.ingredients">
                </c-card>
        {% endfor %}

</div>

cocktailProject/templates/partials/delete.html
<form action="">
    {% csrf_token %}
    <c-button type="danger"></c-button>>
</form>    