cocktailProject/cocktailProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls'))
]

cocktailProject/core/urls.py
from django.urls import path
from .views import CocktailListView,DeleteCocktailView, EditCocktailView, CreateCocktailView,DetailsCocktailView, test_one, test_two, test_three

urlpatterns = [
    path('',CocktailListView.as_view(),name='dashboard'),
    path('create/',CreateCocktailView.as_view(),name='create'),
    path('details<int:pk>/',DetailsCocktailView.as_view(),name='details'),
    path('edit/<int:pk>/',EditCocktailView.as_view(),name='edit'),
    path('delete/<int:pk>/',DeleteCocktailView.as_view(),name='delete'),
    path('one/',test_one,name='one'),
    path('two/',test_two,name='two'),
    path('three/',test_three,name='three'),
]

cocktailProject/core/models.py
from django.db import models

# Create your models here.
class Cocktail(models.Model):
    COCKTAIL_TYPES = [
        ('shaken', 'Shaken'),
        ('stirred', 'Stirred'),
        ('built', 'Built'),
        ('frozen', 'Frozen'),
        ('blended', 'Blended'),
    ]

    STYLE_CHOICES = [
        ('tiki', 'Tiki'),
        ('modern', 'Modern'),
        ('sour', 'Sour'),
    ]

    name = models.CharField(max_length=100)
    type = models.CharField(max_length=10, choices=COCKTAIL_TYPES, blank=True, null=True)
    style = models.CharField(max_length=10, choices=STYLE_CHOICES, blank=True, null=True)
    instructions = models.TextField(blank=True, null=True)
    creator = models.CharField(max_length=100, blank=True, null=True)  # New field

    def __str__(self):
        return self.name

class Ingredient(models.Model):
    TYPE_CHOICES = [
        ('spirit', 'Spirit'),
        ('modified_spirit', 'Modified Spirit'),
        ('citrus', 'Citrus'),
        ('bitters', 'Bitters'),
        ('liqueur', 'Liqueur'),
        ('sweetener', 'Sweetener'),
        ('fruit_puree', 'Fruit/Puree'),
        ('herb_spice', 'Herb/Spice'),
        ('garnish', 'Garnish'),
        ('dairy_cream', 'Dairy/Cream'),
        ('syrup_flavoring', 'Syrup/Flavoring'),
        ('vegetable', 'Vegetable'),
        ('wine_fortified_wine', 'Wine/Fortified Wine'),
        ('extract', 'Extract'),
        ('ice', 'Ice'),
    ]

    name = models.CharField(max_length=100)
    ingredient_type = models.CharField(max_length=20, choices=TYPE_CHOICES)
    brand = models.CharField(max_length=100, blank=True, null=True)
    abv = models.DecimalField("Alcohol by Volume (%)", max_digits=5, decimal_places=1, blank=True, null=True)
    sweetness = models.DecimalField("Sweetness (%)", max_digits=5, decimal_places=2, blank=True, null=True)
    acid = models.DecimalField("Acid (%)", max_digits=5, decimal_places=2, blank=True, null=True)
    instructions = models.TextField("How to create", blank=True, null=True)

    def __str__(self):
        return f"{self.name}"

class CocktailIngredient(models.Model):
    cocktail = models.ForeignKey(Cocktail, related_name='ingredients', on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    quantity = models.FloatField(blank=True, null=True)
    unit = models.CharField(max_length=20, choices=[
        ('Slice', 'slice'),
        ('Wedge', 'wedge'),
        ('Drop', 'drop'),
        ('Dash', 'dash'),
        ('Milliliter', 'ml'),
        ('Ounce', 'oz'),
        ('Cup', 'c'),
    ], blank=True, null=True)
    
    def get_abbreviated_unit(self):
        abbreviations = {
            'milliliter': 'ml',
            'ounce': 'oz',
            'cup': 'c',
        }
        # Return the abbreviation if available; otherwise, return the full unit name
        return abbreviations.get(self.unit, self.unit)

    def __str__(self):
        return f'{self.quantity} {self.unit} of {self.ingredient.name}'

cocktailProject/templates/cotton/button.html
<c-vars type="primary"/>

{% if type == 'danger' %}

    <button class="mt-3 inline-flex w-full justify-center rounded-md bg-red-600 px-3 py-2 text-sm font-semibold text-white shadow-xs hover:bg-red-500 sm:mt-0 sm:ml-3 sm:w-auto" {{ attrs }}>
        <span>{{ slot }}</span>
    </button>

{% elif type == 'primary' %}

    <button class="mt-3 inline-flex w-full justify-center rounded-md bg-blue-600 px-3 py-2 text-sm font-semibold text-white shadow-xs hover:bg-blue-500 sm:mt-0 sm:w-auto" {{ attrs }}>
        <span>{{ slot }}</span>
    </button>

{% else %}

    <button class="inline-flex w-full justify-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 ring-1 shadow-xs ring-gray-300 ring-inset hover:bg-gray-50 sm:mt-0 sm:w-auto" {{ attrs }}>
        <span>{{ slot }}</span>
    </button>

{% endif %}

cocktailProject/templates/cotton/card.html
 <!-- main card container -->
 <div x-cloak
      x-data="{ showSpecs: false, visible: true }"
      x-effect="visible = $store.search.query === '' || 
      '{{ name }}'.toLowerCase().includes($store.search.query.toLowerCase()) || 
      '{{ type }}'.toLowerCase().includes($store.search.query.toLowerCase()) ||
      '{{ drink_style }}'.toLowerCase().includes($store.search.query.toLowerCase());
      $store.visibleCount.update();"
      x-show="visible"
      :class="{ 'card_invisible': !visible }"
      x-transition:enter="ease-out duration-300" 
      x-transition:enter-start="opacity-0" 
      x-transition:enter-end="opacity-100" 
      x-transition:leave="ease-in duration-200" 
      x-transition:leave-start="opacity-100" 
      x-transition:leave-end="opacity-0" 
      class="block card_element p-6 mt-4 bg-white border border-gray-200 rounded-lg shadow transition-all duration-300 ease-in-out"
    >
 <!-- card title and control -->
 <div class="flex items-center justify-between">
     <div>
         <h5 class="text-2xl font-bold tracking-tight text-gray-900">{{ name }}</h5>
     </div>
     <!-- Menu popup -->
     <div>
         <button
             @click="showSpecs = !showSpecs"
             class="p-2 rounded hover:bg-gray-100 transition" 
             aria-label="Show specs"
         >
             <!-- Icon -->
              <!-- Cheveron Down -->
             <svg x-show="!showSpecs" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="w-5 h-5">
                 <path d="M233.4 406.6c12.5 12.5 32.8 12.5 45.3 0l192-192c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0L256 338.7 86.6 169.4c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3l192 192z"/></svg>
              <!-- Cheveron UP -->
             <svg x-show="showSpecs" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="w-5 h-5">
                 <path d="M233.4 105.4c12.5-12.5 32.8-12.5 45.3 0l192 192c12.5 12.5 12.5 32.8 0 45.3s-32.8 12.5-45.3 0L256 173.3 86.6 342.6c-12.5 12.5-32.8 12.5-45.3 0s-12.5-32.8 0-45.3l192-192z"/></svg>
         </button>
     </div>
 </div>

 <!-- card subtitle -->
 <p class="text-gray-800 italic">
    {{ creator }}
     <span class="text-gray-500 text-xs uppercase font-semibold not-italic">| {{ type }},</span>
     <span class="text-gray-500 text-xs uppercase font-semibold not-italic"> {{ drink_style }}</span>
 </p>

 <!-- specs: ingredients and instructions -->
 <div x-show="showSpecs" 
      x-transition:enter="transition ease-out duration-300" 
      x-transition:enter-start="max-h-0 opacity-0" 
      x-transition:enter-end="max-h-screen opacity-100" 
      x-transition:leave="transition ease-in duration-300" 
      x-transition:leave-start="max-h-screen opacity-100" 
      x-transition:leave-end="max-h-0 opacity-0" 
      class="overflow-hidden">
     <!-- card divider -->
     <hr class="my-3">
     <div class="mb-3">
        {% for ingredient in ingredients %}
            <p class="font-normal text-gray-700">
                {{ ingredient.quantity|floatformat }} {{ ingredient.get_unit_display }} {{ ingredient.ingredient.name }}
            </p>
        {% endfor %}
     </div>
     <div>
         <p class="font-normal text-gray-700 mb-3">
            {{ instructions }}
         </p>
     </div>
     <!-- card footer -->
      <div class="flex justify-center gap-2 text-sm">
          <button x-data="{}" @click="$dispatch('modal-open', {title: '{{ name }}', item_id: '{{ item_id }}'})" {{ attrs }} class="rounded text-sm text-red-700 text-left py-2 px-4 hover:bg-red-100 transition" href="#">Delete</button>
          <c-link button_type="secondary" url="#">Edit</c-link>
          <c-link button_type="secondary" url="#">More Details</c-link>
      </div>
 </div>
</div>

cocktailProject/templates/cotton/field_label.html
<label class="block text-sm/6 font-medium text-gray-900" for="{{ field.id_for_label }}">{{ field.name|title }}</label>

cocktailProject/templates/cotton/link_button.html
<a href="{% url url %}" 
   class="mt-3 inline-flex w-full justify-center rounded-md bg-red-600 px-3 py-2 text-sm font-semibold text-white shadow-xs hover:bg-red-500 sm:mt-0 sm:ml-3 sm:w-auto" {{ attrs }}>
    <span>{{ slot }}</span>
</a>

cocktailProject/templates/cotton/menu_popup.html
<!-- Menu popup -->
<div x-data="{ showMenu: false }" class="relative">
    <button 
        @click="showMenu = !showMenu" 
        type="button"
        class="p-2 rounded hover:bg-gray-100 transition" 
        aria-label="More options"
    >
        <!-- Icon -->
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" class="w-5 h-5">
            <path d="M8 256a56 56 0 1 1 112 0A56 56 0 1 1 8 256zm160 0a56 56 0 1 1 112 0 56 56 0 1 1 -112 0zm216-56a56 56 0 1 1 0 112 56 56 0 1 1 0-112z" />
        </svg>
    </button>
    <div x-show="showMenu" 
        @click.away="showMenu = false" 
        x-transition:enter="ease-out duration-300" 
        x-transition:enter-start="opacity-0" 
        x-transition:enter-end="opacity-100" 
        class="absolute flex flex-col gap-1 right-6 top-8 bg-white border border-gray-200 rounded-lg shadow-lg p-2 w-40 transition-all">
        <a class="text-sm text-gray-700 text-left py-2 px-4 rounded-lg hover:bg-gray-100 transition" href="{{ details_url }}">Details</a>
        <a class="text-sm text-gray-700 text-left py-2 px-4 rounded-lg hover:bg-gray-100 transition" href="{{ edit_url }}">Edit</a>
        <hr>
        <a class="text-sm text-red-700 text-left py-2 px-4 rounded-lg hover:bg-red-100 transition" href="{{ delete_url }}">Delete</a>
    </div>
</div>

cocktailProject/templates/cotton/modal.html
<div
    x-cloak
    x-data="{ open: false, title:'', item_id: '0' }" 
     x-on:keydown.window.escape="open = false" 
     x-on:modal-open.window="open = true; title = $event.detail.title; item_id = $event.detail.item_id" 
     x-on:modal-close.window="open = false"
     x-show="open" 
     class="relative z-10" 
     aria-labelledby="modal-title" 
     x-ref="dialog" 
     aria-modal="true">

    <!-- Modal Background -->
    <div x-show="open" 
         x-transition:enter="ease-out duration-300" 
         x-transition:enter-start="opacity-0" 
         x-transition:enter-end="opacity-100" 
         x-transition:leave="ease-in duration-200" 
         x-transition:leave-start="opacity-100" 
         x-transition:leave-end="opacity-0" 
         class="fixed inset-0 bg-gray-500/75 transition-opacity" 
         aria-hidden="true"></div>

    <!-- Modal Content -->
    <div class="fixed inset-0 z-10 flex items-end sm:items-center justify-center p-4">
        <div x-show="open" 
             x-transition:enter="ease-out duration-300" 
             x-transition:enter-start="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95" 
             x-transition:enter-end="opacity-100 translate-y-0 sm:scale-100" 
             x-transition:leave="ease-in duration-200" 
             x-transition:leave-start="opacity-100 translate-y-0 sm:scale-100" 
             x-transition:leave-end="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95" 
             class="relative transform overflow-hidden rounded-lg bg-white shadow-xl sm:w-full sm:max-w-lg" 
             @click.away="open = false">
            
            <!-- Header Slot -->
            <div class="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
                <div class="sm:flex sm:items-start">
                    <div class="mx-auto flex h-12 w-12 flex-shrink-0 items-center justify-center rounded-full bg-red-100 sm:mx-0 sm:h-10 sm:w-10">
                        <slot name="modal_icon">
                            <!-- Default icon -->
                            <svg class="h-6 w-6 text-red-600" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126ZM12 15.75h.007v.008H12v-.008Z"></path>
                            </svg>
                        </slot>
                    </div>
                    <div class="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left">
                        <slot name="modal_title">
                            <h3 class="text-lg font-medium leading-6 text-gray-900" id="modal-title">
                                Delete <span x-text="title"></span>
                            </h3>
                        </slot>
                        <slot name="modal_body">
                            <div class="mt-2">
                                <p class="text-sm text-gray-500">Are you sure you want to remove this item? This action cannot be undone.</p>
                            </div>
                        </slot>
                    </div>
                </div>
            </div>

            <!-- Footer Slot -->
            <div class="bg-gray-50 px-4 py-3 sm:flex sm:flex-row-reverse items-center sm:px-6">
                <slot name="modal_footer">
                        <c-button ::hx-delete="`/delete/${item_id}/`"
                                  hx-target="#card_list" 
                                  type="danger"
                                  ::test="item_id"
                                  @click="open = false">
                            Confirm Delete
                        </c-button>
                    <c-button type="secondary"  @click="open = false">
                        Cancel
                    </c-button>
                </slot>
            </div>
        </div>
    </div>
</div>

cocktailProject/templates/cotton/navigation.html
<header class="relative z-20 w-full flex-none text-sm/6 font-semibold text-slate-900">
    <nav aria-label="Global" class="max-w-container mx-auto px-4 sm:px-6 lg:px-8">
        <div class="relative flex justify-between items-center py-[2.125rem]">
            <span class="">AppName</span>
            <div class="hidden sm:flex gap-10">
                {% for link in links  %}
                    <a class="font-semibold" href="{% url link.url %}">{{ link.name }}</a>
                {% endfor %}
            </div>
            <a class="hidden sm:block" href="#">Logout</a>
            <button id="toggleModal" type="button" class="-my-1 -mr-1 ml-6 flex size-8 items-center justify-center sm:hidden"><span class="sr-only">Open navigation</span><svg viewBox="0 0 24 24" class="size-6 stroke-slate-900"><path d="M3.75 12h16.5M3.75 6.75h16.5M3.75 17.25h16.5" fill="none" stroke-width="1.5" stroke-linecap="round"></path></svg></button>
        </div>
    </nav>
</header>
    <nav class="mobile-menu fixed top-0 right-0 z-50 min-w-80 bg-white h-screen text-base/7 text-slate-900 translate-x-full transition-all ease-in-out duration-700">
        <div class="flex flex-col items-start">
            <div class="px-8 py-6 w-full">
                <div class="flex flex-row justify-between">
                    <div>AppName</div>
                    <button id="closeNav" type="button" class="absolute top-5 right-6 flex size-8 items-center justify-center"><span class="sr-only">Close navigation</span><svg class="h-3.5 w-3.5 overflow-visible stroke-slate-900" fill="none" stroke-width="1.5" stroke-linecap="round" xmlns="http://www.w3.org/2000/svg"><path d="M0 0L14 14M14 0L0 14"></path></svg></button>
                </div>
            </div>
            <div class="px-8 py-6 border-1 border-y border-solid w-full">
                    {% for link in links  %}
                        <a class="block w-full py-2 mb-4 font-semibold" href="{% url link.url %}">{{ link.name }}</a>
                    {% endfor %}
            </div>
            <div class="px-8 py-6 w-full">
                <div class="-my-2 space-y-4">
                    <a class="block w-full py-2 font-semibold" href="#">Log In</a>
                    <a class="inline-flex justify-center rounded-lg text-sm font-semibold py-3 px-4 bg-slate-900 text-white hover:bg-slate-700 w-full" href="#"><span>Log In</span></a>
                </div>
            </div>
        </div>
    </nav>

<div id="overlay" class="fixed z-20 inset-0 bg-black/20 backdrop-blur-sm opacity-0 pointer-events-none transion-all duration-700"></div>

<script>
const navElement = document.querySelector('nav.mobile-menu');
const toggleModal = document.getElementById('toggleModal');
const closeModal = document.getElementById('closeNav');
const overlay = document.getElementById('overlay');

toggleModal.addEventListener('click', ()=>{
    navElement.classList.toggle('translate-x-0')
    overlay.classList.toggle('opacity-0');
    overlay.classList.toggle('pointer-events-none');
})

closeModal.addEventListener('click', ()=>{
    navElement.classList.toggle('translate-x-0')
    overlay.classList.toggle('opacity-0');
    overlay.classList.toggle('pointer-events-none');
})

overlay.addEventListener('click',()=>{
    navElement.classList.toggle('translate-x-0')
    overlay.classList.toggle('opacity-0');
    overlay.classList.toggle('pointer-events-none');
})
</script>

cocktailProject/templates/cotton/search_input.html
<div
    x-data="{ search: ''}"

    >
    <label for="search" class="block text-sm/6 font-medium text-gray-900 sr-only">Search</label>
    <div class="mt-2">
      <div class="flex items-center rounded-md bg-white pl-3 outline outline-1 -outline-offset-1 outline-gray-300 has-[input:focus-within]:outline has-[input:focus-within]:outline-2 has-[input:focus-within]:-outline-offset-2 has-[input:focus-within]:outline-indigo-600">
        <div class="grid shrink-0 grid-cols-1 focus-within:relative">
          <svg class="pointer-events-none col-start-1 row-start-1 mr-2 size-5 self-center justify-self-end text-gray-500 sm:size-4" viewBox="0 0 512 512" fill="currentColor" aria-hidden="true" data-slot="icon">
            <path d="M416 208c0 45.9-14.9 88.3-40 122.7L502.6 457.4c12.5 12.5 12.5 32.8 0 45.3s-32.8 12.5-45.3 0L330.7 376c-34.4 25.2-76.8 40-122.7 40C93.1 416 0 322.9 0 208S93.1 0 208 0S416 93.1 416 208zM208 352a144 144 0 1 0 0-288 144 144 0 1 0 0 288z"/></svg>
        </div>
        <input 
            x-model="$store.search.query"
            @input="$store.visibleCount.update()"
            type="search"
            name="search" 
            id="search" 
            class="block min-w-0 grow py-1.5 pl-1 pr-3 text-base text-gray-900 placeholder:text-gray-400 focus:outline focus:outline-0 sm:text-sm/6" 
            placeholder="Search...">
      </div>
    </div>
  </div>

cocktailProject/templates/cotton/select_field.html
<div {{ attrs }}>
    <c-field_label :field="{{ field }}"></c-field_label>
    <div class="grid grid-cols-1 mt-2">
        <select class="outline-gray-300 -outline-offset-1 outline outline-1 text-gray-900 text-base ps-3 pe-8 py-1.5 bg-white rounded-md appearance-none w-full row-start-1 col-start-1 focus:outline-indigo-600 focus:outline-2 focus:-outline-offset-2" 
                name="{{ field.id_for_label }}" 
                id="{{ field.id_for_label }}">
                    {% for value, label in field.field.choices %}
                        <option value="{{ value }}" {% if field.value == value %}selected{% endif %}>{{ label }}</option>
                    {% endfor %}
        </select>
        <svg xmlns="http://www.w3.org/2000/svg" 
             viewBox="0 0 16 16" 
             fill="currentColor" 
             aria-hidden="true" 
             data-slot="icon" 
             class="size-4 text-gray-500 self-center justify-self-end me-2 row-start-1 col-start-1 pointer-events-none">
                <path fill-rule="evenodd" d="M4.22 6.22a.75.75 0 0 1 1.06 0L8 8.94l2.72-2.72a.75.75 0 1 1 1.06 1.06l-3.25 3.25a.75.75 0 0 1-1.06 0L4.22 7.28a.75.75 0 0 1 0-1.06Z" clip-rule="evenodd"></path>
            </svg>
    </div>
    <c-help_text :field="{{ field }}"></c-help_text>
    {% if field.errors %}
        <div class="text-red-500 text-sm font-medium italic ps-1">
        {{ field.errors }}
        </div>
    {% endif %}
</div>

cocktailProject/templates/cotton/success_modal.html
<div
    x-cloak
    x-data="{ open: true, title:'', item_id: '0' }" 
     x-on:keydown.window.escape="open = false" 
     x-on:modal-open.window="open = true; title = $event.detail.title; item_id = $event.detail.item_id" 
     x-on:modal-close.window="open = false"
     x-show="open" 
     class="relative z-10" 
     aria-labelledby="modal-title" 
     x-ref="dialog" 
     aria-modal="true">

    <!-- Modal Background -->
    <div x-show="open" 
         x-transition:enter="ease-out duration-300" 
         x-transition:enter-start="opacity-0" 
         x-transition:enter-end="opacity-100" 
         x-transition:leave="ease-in duration-200" 
         x-transition:leave-start="opacity-100" 
         x-transition:leave-end="opacity-0" 
         class="fixed inset-0 bg-gray-500/75 transition-opacity" 
         aria-hidden="true"></div>

    <!-- Modal Content -->
    <div class="fixed inset-0 z-10 flex items-end sm:items-center justify-center p-4">
        <div x-show="open" 
             x-transition:enter="ease-out duration-300" 
             x-transition:enter-start="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95" 
             x-transition:enter-end="opacity-100 translate-y-0 sm:scale-100" 
             x-transition:leave="ease-in duration-200" 
             x-transition:leave-start="opacity-100 translate-y-0 sm:scale-100" 
             x-transition:leave-end="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95" 
             class="relative transform overflow-hidden rounded-lg w-full sm:m-auto sm:max-w-md bg-white shadow-xl " 
             @click.away="open = false">
            
            <!-- Header Slot -->
            <div class="bg-white px-4 pt-5 pb-4">
                <div class="flex flex-col items-center justify-center">
                    <button @click="open = false" 
                            type="button" 
                            class="text-gray-400 absolute top-2.5 right-2.5 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-toggle="successModal">
                        <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                        <span class="sr-only">Close modal</span>
                    </button>
                    <div class="mx-auto flex h-12 w-12 flex-shrink-0 items-center justify-center rounded-full bg-green-100 ">
                        <slot name="modal_icon">
                            <!-- Default icon -->
                            <svg aria-hidden="true" class="w-8 h-8 text-green-500 dark:text-green-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                            <span class="sr-only">Success</span>
                        </slot>
                    </div>
                    <div class="mt-3 text-center">
                        <slot name="modal_body">
                            <div class="mt-2">
                                <p class="mb-4 text-lg font-semibold text-gray-900 dark:text-white">Successfully deleted {{ deleted_item }}.</p>
                            </div>
                        </slot>
                    </div>
                </div>
            </div>

            <!-- Footer Slot -->
            <div class="bg-gray-50 px-4 py-3 flex justify-center">
                <slot name="modal_footer">
                    <c-button type="primary"  @click="open = false">
                        Continue
                    </c-button>
                </slot>
            </div>
        </div>
    </div>
</div>

cocktailProject/templates/cotton/tab.html
<div {{ attrs }} x-show="tab === '{{ name }}'">
    {{ slot }}
</div>

cocktailProject/templates/cotton/tabs.html
<!-- Receives a list of tabs and iterates through to create the tab buttons -->
<div 
    x-data="{tab: '{{ tabs|first }}'}"
    x-cloak>
    <!-- After defaulting to the first entry in the list, loops through the list -->
    <div class="flex flex-wrap text-sm font-medium text-center text-gray-500 border-b border-gray-200 dark:border-gray-700 dark:text-gray-400">
        {% for tab in tabs %}
            <div class="me-2">
                <button
                    @click="tab='{{ tab }}'" 
                    type="button"
                    :class="tab==='{{ tab }}' ? ['text-blue-600', 'bg-gray-100'] : ['text-gray-500','hover:text-gray-600','hover:bg-gray-50']" 
                    class="inline-block p-4 rounded-t-lg">{{ tab|title }}</button>
            </div>
        {% endfor %} 
    </div>
    <!-- Actual tab content -->
    <div>
        <!-- This is where the content lives -->
        {{ slot }}
    </div>
</div>

cocktailProject/templates/cotton/text_field.html
<div class="{{ class }}">
    <c-field_label :field="{{ field }}"></c-field_label>
    <div class="grid grid-cols-1 mt-2">
        <input class="outline-gray-300 -outline-offset-1 outline outline-1 text-gray-900 text-base px-3 py-1.5 bg-white rounded-md appearance-none w-full row-start-1 col-start-1 focus:outline-indigo-600 focus:outline-2 focus:-outline-offset-2" 
                name="{{ field.id_for_label }}" 
                id="{{ field.id_for_label }}"
                {{ attrs }}>
        </input>
    </div>
    <c-help_text :field="{{ field }}"></c-help_text>
    {% if field.errors %}
        <div class="text-red-500 text-sm font-medium italic ps-1">
        {{ field.errors }}
        </div>
    {% endif %}
</div>

cocktailProject/templates/cotton/textarea_field.html
<div>
    <c-field_label :field="{{ field }}"></c-field_label>
    <div class="grid grid-cols-1 mt-2">
        <textarea class="outline-gray-300 -outline-offset-1 outline outline-1 text-gray-900 text-base px-3 py-1.5 bg-white rounded-md appearance-none w-full row-start-1 col-start-1 focus:outline-indigo-600 focus:outline-2 focus:-outline-offset-2"
                aria-describedby="{{ field.id_for_label }}-help {{ field.id_for_label }}-error" 
                name="{{ field.id_for_label }}" 
                id="{{ field.id_for_label }}"
                {{ attrs }}></textarea>
    </div>
    <c-help_text :field="{{ field }}"></c-help_text>
    {% if field.errors %}
        <div class="text-red-500 text-sm font-medium italic ps-1">
        {{ field.errors }}
        </div>
    {% endif %}
</div>